name: release
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Set up Python 3.7
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and push sphinx documentation
      run: |
        cd docs
        make html
        cd _build/html
        touch .nojekyll
        export REV=$(git rev-parse --short HEAD)
        git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +gh-pages:refs/remotes/origin/gh-pages
        git checkout --detach
        GIT_WORK_TREE=. git reset --mixed origin/gh-pages
        GIT_WORK_TREE=. git add .
        GIT_WORK_TREE=. git -c user.name="Github Action" -c user.email="autogen@github.invalid" commit -m "rebuild docs from $REV"
        GIT_WORK_TREE=. git push origin HEAD:gh-pages
