name: release
on:
  push:
    branches:
    - master

jobs:
  release:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Set up Python 3.7
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.7
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      run: |
        cd docs
        make html
        cd _build/html
        touch .nojekyll
    - name: Push to gh-pages
      env:
        PERSONAL_TOKEN: ${{ secrets.PAGES_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/_build/html
        SCRIPT_MODE: true
        INPUT_EMPTYCOMMITS: false
      run: |
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.9.0/entrypoint.sh
        bash ./entrypoint.sh